"""Funded x402 buyer bootstrap — prove the paid surface end-to-end.

Drives the OFFICIAL x402 Python SDK (the same client any real agent uses)
against a live Groundcheck deployment: parse the 402 offer, build and sign a
v2 EIP-3009 payment, retry, and collect the settlement receipt. A successful
mainnet settle is also what triggers CDP Bazaar indexing of the endpoint.

Commands
  generate   mint a throwaway buyer wallet -> env file (address printed,
             key never printed)
  dry-run    unfunded proof: 402 parses, payment builds+signs, server verify
             rejects for insufficient funds (expected) — everything but money
  pay        pay one endpoint for real (--path /extract | /attest-delivery)
  loop       the full demo: pay /extract, then pay /attest-delivery to buy a
             SIGNED DELIVERY RECEIPT of that very purchase, then verify the
             receipt offline against the engine's attest module. One command,
             the whole "payment -> delivery -> accountability" story.

Setup (one-time)
  python3 -m venv scripts/.buyer-venv
  scripts/.buyer-venv/bin/pip install "x402[evm,requests]>=2.15,<3" cryptography
  scripts/.buyer-venv/bin/python scripts/buyer_bootstrap.py generate
  # fund the printed address with ~$1 USDC on Base mainnet (no ETH needed —
  # EIP-3009 is gasless for the payer; the facilitator sponsors gas)

Run
  set -a; source ~/Documents/Private_Vault/groundcheck/buyer-wallet.env; set +a
  scripts/.buyer-venv/bin/python scripts/buyer_bootstrap.py dry-run
  scripts/.buyer-venv/bin/python scripts/buyer_bootstrap.py loop

The private key travels ONLY via the X402_BUYER_KEY env var; this script
never prints it and artifacts under scripts/out/ contain no key material.
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import stat
import sys

import requests

DEFAULT_HOST = "https://groundcheck.seiche.info"
OUT_DIR = pathlib.Path(__file__).parent / "out"
WALLET_ENV = pathlib.Path.home() / "Documents/Private_Vault/groundcheck/buyer-wallet.env"

EXTRACT_BODY = {"text": "The Eiffel Tower was completed in 1889. "
                        "It is 330 metres tall."}


def _die(msg: str) -> "NoReturn":  # noqa: F821
    print(f"✗ {msg}", file=sys.stderr)
    sys.exit(1)


def _save(name: str, payload: dict) -> pathlib.Path:
    OUT_DIR.mkdir(exist_ok=True)
    p = OUT_DIR / name
    p.write_text(json.dumps(payload, indent=2))
    return p


# ---------------------------------------------------------------------------
# wallet
# ---------------------------------------------------------------------------
def cmd_generate(_args) -> None:
    from eth_account import Account

    if WALLET_ENV.exists():
        _die(f"{WALLET_ENV} already exists — refusing to overwrite a wallet "
             "that may hold funds. Delete it yourself if it is truly disposable.")
    acct = Account.create()
    WALLET_ENV.parent.mkdir(parents=True, exist_ok=True)
    WALLET_ENV.write_text(
        "# throwaway x402 buyer wallet (Base mainnet) — generated by "
        "buyer_bootstrap.py\n"
        f"X402_BUYER_ADDRESS={acct.address}\n"
        f"X402_BUYER_KEY={acct.key.hex()}\n")
    WALLET_ENV.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600
    print(f"✓ wallet written to {WALLET_ENV} (chmod 600)")
    print(f"  address: {acct.address}")
    print("\nNext: fund it with ~$1 USDC on BASE MAINNET (chain id 8453).")
    print("  - USDC contract: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913")
    print("  - No ETH needed (EIP-3009 gasless; facilitator sponsors gas).")
    print("  - Then: set -a; source " + str(WALLET_ENV) + "; set +a")


# ---------------------------------------------------------------------------
# SDK client
# ---------------------------------------------------------------------------
def _http_client():
    """An official-SDK buyer registered for Base mainnet + Sepolia."""
    from eth_account import Account
    from x402.client import x402ClientSync
    from x402.http import x402HTTPClientSync
    from x402.mechanisms.evm.exact.client import ExactEvmScheme
    from x402.mechanisms.evm.signers import EthAccountSigner

    key = os.environ.get("X402_BUYER_KEY", "").strip()
    if not key:
        _die("X402_BUYER_KEY is not set. Run `generate`, fund the address, "
             "then `set -a; source " + str(WALLET_ENV) + "; set +a`.")
    acct = Account.from_key(key)
    scheme = ExactEvmScheme(signer=EthAccountSigner(acct))
    client = x402ClientSync()
    for network in ("eip155:8453", "eip155:84532"):
        client.register(network, scheme)
    return x402HTTPClientSync(client), acct.address


def _pay_once(host: str, path: str, body: dict, label: str) -> tuple[dict, str, dict]:
    """402 -> sign -> retry. Returns (response_json, raw_settle_header, settle)."""
    http, address = _http_client()
    url = f"{host}{path}"

    r1 = requests.post(url, json=body, timeout=60)
    if r1.status_code == 200:
        print(f"  note: {path} answered 200 without payment (free quota) — "
              "result still counts, but no settle happened")
        return r1.json(), "", {}
    if r1.status_code != 402:
        _die(f"{path}: expected 402, got {r1.status_code}: {r1.text[:300]}")

    pr = http.get_payment_required_response(
        lambda h: r1.headers.get(h), body=r1.json())
    offer = pr.accepts[0]
    amount = getattr(offer, "amount", None) or getattr(
        offer, "max_amount_required", "?")
    print(f"  402 parsed by official SDK: {offer.network}, "
          f"amount {amount} (atomic USDC), payTo {offer.pay_to}")

    payload = http.create_payment_payload(pr)
    headers = http.encode_payment_signature_header(payload)
    print(f"  payment built + signed by {address}; retrying with "
          f"{'/'.join(headers)}")

    r2 = requests.post(url, json=body, headers=headers, timeout=120)
    if r2.status_code == 402:
        reason = (r2.json() or {}).get("error", r2.text[:200])
        return {}, "", {"rejected": reason}
    if r2.status_code != 200:
        _die(f"{path}: paid retry got {r2.status_code}: {r2.text[:300]}")

    raw_settle = (r2.headers.get("X-PAYMENT-RESPONSE")
                  or r2.headers.get("PAYMENT-RESPONSE") or "")
    settle = {}
    try:
        s = http.get_payment_settle_response(lambda h: r2.headers.get(h))
        settle = s.model_dump(mode="json") if hasattr(s, "model_dump") else dict(s)
    except Exception as exc:  # settle header shape varies by facilitator
        settle = {"decode_note": f"{type(exc).__name__}: {exc}"}

    result = r2.json()
    _save(f"{label}-response.json", result)
    _save(f"{label}-settle.json", {"raw_header": raw_settle, "decoded": settle})
    tx = settle.get("transaction") or settle.get("tx_hash") or ""
    print(f"✓ PAID {path}: settled={settle.get('success')} tx={tx or '?'}")
    if tx:
        print(f"  https://basescan.org/tx/{tx}")
    return result, raw_settle, settle


# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------
def cmd_dry_run(args) -> None:
    """Everything except money: parse, sign, submit, expect verify-rejection."""
    host = args.host.rstrip("/")
    print(f"dry-run against {host}/extract (unfunded wallet is fine)")
    result, _raw, settle = _pay_once(host, "/extract", EXTRACT_BODY, "dryrun")
    if settle.get("rejected"):
        print(f"✓ dry-run complete: server verify rejected the unfunded "
              f"payment as expected -> {settle['rejected']!r}")
        print("  (the 402 parsed, the payment signed, the server spoke to the "
              "facilitator — only funding is missing)")
    elif result:
        print("✓ dry-run got a real result — wallet already funded or free "
              "quota served it")


def cmd_pay(args) -> None:
    host = args.host.rstrip("/")
    paths = (["/extract", "/attest-delivery"] if args.path == "all"
             else [args.path])
    for path in paths:
        body = EXTRACT_BODY if path == "/extract" else {
            "service": f"{host}/extract",
            "response_text": json.dumps(EXTRACT_BODY),
            "advertised_schema": {"type": "object", "required": ["text"]},
        }
        result, _raw, settle = _pay_once(host, path, body, path.strip("/"))
        if settle.get("rejected"):
            _die(f"{path}: payment rejected: {settle['rejected']}")


def cmd_loop(args) -> None:
    """Pay /extract, then buy a signed delivery receipt OF that purchase,
    then verify the receipt offline. The full accountability story."""
    host = args.host.rstrip("/")

    print("[1/3] paying /extract ($0.005) …")
    extract_result, raw_settle, settle = _pay_once(
        host, "/extract", EXTRACT_BODY, "loop-extract")
    if settle.get("rejected"):
        _die(f"/extract payment rejected: {settle['rejected']}")

    print("[2/3] paying /attest-delivery ($0.05) for a signed delivery "
          "receipt of that exact purchase …")
    delivery_body = {
        "service": f"{host}/extract",
        "request_text": json.dumps(EXTRACT_BODY),
        "response_text": json.dumps(extract_result),
        "advertised_schema": {
            "type": "object",
            "required": ["count", "claims", "input_sha256"],
            "properties": {"claims": {"type": "array"}},
        },
    }
    if raw_settle:
        delivery_body["payment_receipt"] = raw_settle
    receipt, _raw2, settle2 = _pay_once(
        host, "/attest-delivery", delivery_body, "loop-delivery")
    if settle2.get("rejected"):
        _die(f"/attest-delivery payment rejected: {settle2['rejected']}")

    print(f"  delivery_verdict: {receipt.get('delivery_verdict')!r} — "
          f"{receipt.get('rationale')}")
    pay = receipt.get("payment") or {}
    print(f"  payment bound: {pay.get('bound')} tx={pay.get('transaction')}")

    print("[3/3] verifying the delivery receipt OFFLINE "
          "(engine attest module, no network) …")
    engine_dir = pathlib.Path(__file__).resolve().parents[1] / "engine"
    sys.path.insert(0, str(engine_dir))
    from groundcheck_engine import attest  # noqa: E402

    verdict = attest.verify_attested_response("delivery", receipt)
    if not verdict["valid"]:
        _die(f"offline verification FAILED: {verdict['problems']}")
    print("✓ receipt verifies offline: Ed25519 signature + manifest hash "
          "recompute from the saved JSON alone")
    print(f"\nArtifacts in {OUT_DIR}/ — loop-delivery-response.json is the "
          "self-contained dispute/demo artifact.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--host", default=os.environ.get("GROUNDCHECK_HOST",
                                                     DEFAULT_HOST))
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("generate")
    sub.add_parser("dry-run")
    pay = sub.add_parser("pay")
    pay.add_argument("--path", choices=["/extract", "/attest-delivery", "all"],
                     default="all")
    sub.add_parser("loop")
    args = ap.parse_args()
    {"generate": cmd_generate, "dry-run": cmd_dry_run,
     "pay": cmd_pay, "loop": cmd_loop}[args.cmd](args)


if __name__ == "__main__":
    main()
